config/routes.rb
Rails.application.routes.draw do
  post 'users/login', as: :user_login

  get 'users/:id', to: 'users#show', as: :user

  root 'movies#search'
  get 'movies/search', to: 'movies#search'
  get 'movies/new', to: 'movies#new', as: :new_movie
  resources :movies, only: [:index, :create, :show] do
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :comments
  
  Tmdb::Api.key("3839ff582cb557887f109e2430210268")

  def self.get_movies(query)
    list = Tmdb::Movie.find(query)

    list.delete_if do |movie|
      movie.poster_path.nil? || movie.overview.empty?
    end
    
    list = list.sort_by{ |m| m.popularity }.reverse
    
    list.first(20).map! do |movie|  
      title = movie.title
      poster = "https://image.tmdb.org/t/p/w500" + movie.poster_path
      year = movie.release_date.first(4)
      synopsis = movie.overview

      {title: title, poster: poster, year: year, synopsis: synopsis}
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    Comment.create(username: params[:comment][:username], text: params[:comment][:text], movie_id: params[:movie_id])
    redirect_to movie_path(params[:movie_id])
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: :show

  # GET /movies/search
  def search
    @movie = Movie.new
    @errors = []
  end

  # GET /movies
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  def show
    @comments = Comment.where('movie_id = ?', @movie.id)
    @comment = Comment.new
    @user = User.find_by(id: session[:user_id])
  end

  # GET /movies/new
  def new
    @movie = Movie.find_by('title LIKE ?',"%#{params[:query]}%")
    if @movie.nil?
      @movies = Movie.get_movies params[:query]
      render :new
    else
      redirect_to @movie
    end
  end

  # POST /movies
  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie
    else
      render :search
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :poster, :year, :synopsis)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: :show

  def login
    @user = User.find_by(username: params[:username])
    if @user[:password] == params[:password]
      session[:user_id] = @user.id
      redirect_to users_path(@user[:id])
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def logout
    session[:user_id] = nil
  end

  def show
    @comments = Comment.where('username = ?', @user.username)
  end

  private
    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:username, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies Comments</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">

  </head>

  <body>
    <div class="pure-g">
      <div class="pure-u container">
        <%= yield %> 
      </div>
    </div>
  </body>
</html>

app/views/movies/index.html.erb
<h1>Movies</h1>

<%= link_to 'New Search', root_path, class: "pure-button pure-button-primary"%>

<br><br>

<% @movies.each do |movie| %>
  <div class="pure-g">
    <div class="pure-u-1-5">
      <img src=<%= movie.poster %> alt="poster" width=100%>
    </div>
    <div class="pure-u-4-5">
      <div class="pure-g">
        <div class="pure-u-1">
          <h1><%= movie.title %> (<%= movie.year %>)</h1>
        </div>
      </div>
      <div class="pure-g">
        <div class="pure-u-1">
          <p><%= movie.synopsis %></p>
        </div>
      </div class="pure-g">
      <div class="pure-g">
        <div class="pure-u-1 go-to-movie">
          <%= link_to "Comment #{movie[:title]}", movie_path(:id => movie.id), class: "pure-button pure-button-primary" %>
        </div>
      </div class="pure-g">
    </div>
  </div>
<% end %>

app/views/movies/new.html.erb
<<h1>Select the movie you where looking for:</h1>

<br><br>

<% @movies.each do |movie| %>
  <div class="pure-g">
    <div class="pure-u-1-5">
      <img src=<%= movie[:poster] %> alt="poster" width='100%'>
    </div>
    <div class="pure-u-4-5">
      <div class="pure-g">
        <div class="pure-u-1">
          <h1><%= movie[:title] %> (<%= movie[:year] %>)</h1>
        </div>
      </div>
      <div class="pure-g">
        <div class="pure-u-1">
          <p><%= movie[:synopsis] %></p>
        </div>
      </div class="pure-g">
      <div class="pure-g">
        <div class="pure-u-1 go-to-movie">
          <%= button_to "Comment #{movie[:title]}", movies_path(movie: {title: movie[:title], poster: movie[:poster], year: movie[:year], synopsis: movie[:synopsis]}), class: "pure-button pure-button-primary" %>
        </div>
      </div class="pure-g">
    </div>
  </div>
<% end %>

app/views/movies/search.html.erb
<h1>Search Movie</h1>

<%= form_tag(new_movie_path, method: :get) do %>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Search", class: "pure-button pure-button-primary") %>
<% end %>

app/views/movies/show.html.erb
<%= link_to 'Search another movie', root_path, class: "pure-button pure-button-primary" %>

<br><br>
<div class="pure-g">
  <div class="pure-u">
    <div class="pure-g">
      <div class="pure-u-1-5">
        <img src=<%= @movie.poster %> alt="poster" width='100%'>
      </div>
      <div class="pure-u-4-5">
        <div class="pure-g movie-box">
          <div class="pure-u-1">
            <h2><%= @movie.title %> (<%= @movie.year %>)</h2>
          </div>
        </div>
        <div class="pure-g movie-box">
          <div class="pure-u-1">
            <p class="text-box"><%= @movie.synopsis %></p>
          </div>
        </div>
        <div class="pure-g comment-box">
          <div class="pure-u-1">
            <h3>Discussion</h3>
          </div>
          <% @comments.each do |comment| %>
            <div class="pure-u-1">
              <strong><%= link_to "#{comment.username}", @user %></strong>
              <span class="created-date"><%= time_ago_in_words(comment.created_at) %> ago</span>
            </div>
            <div class="pure-u-1">
              <p class="text-box"><%= comment.text %></p>
            </div>
          <% end %>
          <% if @user.nil? %>
            <div class="pure-u-1">
              <%= form_tag(user_login_path) do %>

                <%= label_tag :username %>
                <%= text_field_tag :username %>

                <%= label_tag :password %>
                <%= password_field_tag :password %>

                <%= submit_tag "Login", class: "pure-button pure-button-primary" %>
              <% end %>
            </div>
          <% else %>
            <div class="pure-u-1">
              <%= form_for([@movie, @comment]) do |f| %>
                
                <%= f.hidden_field :username, :value => @user[:username] %>

                <%= f.label :text %>
                <%= f.text_field :text %>

                <%= submit_tag "Send comment", class: "pure-button pure-button-primary" %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user[:username] %></h1>
<h2>Comments:</h2>
<ul>
  <% @comments.each do |comment| %>
    <li>
    <strong><%= link_to "#{comment.movie.title}", comment.movie %>:</strong>
    <%= comment.text %>
    </li>
  <% end %>
</ul>